build: false

image:
  - Visual Studio 2015

environment:
  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda


install:
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=2.7 numpy scipy nose
  - activate test-environment
  - pip install coverage
  - python setup.py install
  # adding cvxpy
  - cd tests
  - git clone https://github.com/cvxgrp/cvxpy.git
  - cd cvxpy
  - python setup.py install
  - pip install nose

test_script:
  - nosetests cvxpy
