build: false


environment:
  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda
      operating system: linux

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - "conda create -q -n test-environment python=%PYTHON_VERSION% numpy scipy nose"
  - activate test-environment
  - pip install coverage
  - python setup.py install
  # adding cvxpy
  - cd tests
  - git clone https://github.com/cvxgrp/cvxpy.git
  - cd cvxpy
  - python setup.py install
  - pip install nose

test_script:
  - nosetests cvxpy
