build: false

image:
  - Visual Studio 2015


environment:
  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda
for:
-
  matrix:
    only:
        - image: Visual Studio 2015
        
  install:
     - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
     - conda config --set always_yes yes --set changeps1 no
     - conda update -q conda
     - conda info -a
     - "conda create -q -n test-environment python=%PYTHON_VERSION% numpy scipy nose 
     - activate test-environment
     - pip install coverage
     - python setup.py install
     - cd tests
     - git clone https://github.com/cvxgrp/cvxpy.git
     - cd cvxpy
     - python setup.py install
  


test_script:
  - nosetests cvxpy
